### ISSUE TITLE
🎬 Add the GitHub Action `First interaction` 🎬

### ISSUE THREAD

**Issue by jbampton** [One-Language/One#318]
**Is your feature request related to a problem? Please describe.**
Would like to auto greet new people

**Describe the solution you'd like**
https://github.com/marketplace/actions/first-interaction

**Describe alternatives you've considered**
Manual is slower and error prone and also not very fancy 

**Additional context**
Let's come up with something interesting to say on `First interaction` 💯

**Comment by Lightyagami1** [comment]
I can take a stab at this.

so as I understood this, I need to add a `action.yml` at the root of project with content 


```
steps:
- uses: actions/first-interaction@v1
  with:
    repo-token: ${{ secrets.GITHUB_TOKEN }}
    issue-message: 'An action for filtering pull requests and issues from first-time contributors.'
    pr-message: 'An action for filtering pull requests and issues from first-time contributors.'
```
